apiVersion: skaffold/v1beta6
kind: Config
build:
  local: {}
  artifacts:
  - image: hub.docker.com/yaleits/reaper
    docker:
      dockerfile: k8s/Dockerfile
deploy:
  kubectl:
    manifests:
      - k8s/k8s-*
