---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: reaper
spec:
  rules:
  - http:
      paths:
      - path: /v1/reaper
        backend:
          serviceName: reaper
          servicePort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: reaper
  labels:
    app: reaper
    tier: api
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/port:   '8080'
    prometheus.io/path:   '/v1/reaper/metrics'
spec:
  selector:
    app: reaper
    tier: api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: reaper
  labels:
    app: reaper
    tier: api
spec:
  selector:
    matchLabels:
      app: reaper
      tier: api
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: reaper
        tier: api
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: reaper
        image: hub.docker.com/yaleits/reaper
        volumeMounts:
        - name: reaper-config
          mountPath: "/app/config"
          readOnly: true
        livenessProbe:
          httpGet:
            path: /v1/reaper/ping
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 3
      volumes:
      - name: reaper-config
        secret:
          secretName: reaper-config-json
        # envFrom:
        #   - configMapRef:
        #       name: reaper-config
        #   - secretRef:
        #       name: reaper-secrets
