# build stage
FROM golang:alpine AS build-env
RUN apk add --no-cache git openssh-client gcc musl-dev
RUN mkdir /app
WORKDIR /app
COPY go.mod .
COPY go.sum .
RUN go mod download
COPY . .
RUN go test ./... -cover
RUN go build -o /app/api *.go

# final stage
FROM alpine
RUN apk add --no-cache ca-certificates tzdata
WORKDIR /app
COPY --from=build-env /app/api /app/api
EXPOSE 80
ENTRYPOINT ["./api"]
